name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Ver arquivos
        run: ls -la

      - name: Compilar APK
        run: gradle assembleDebug

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: app/build/outputs/apk/debug/*.apk
